import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import profilePic from "public/me.png";
import * as sc from "sc/pages/index";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>about me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <sc.Main>
        <sc.Container>
          <sc.ProfileContainer>
            <Image
              src={profilePic}
              alt="avater"
              layout="fixed"
              height={100}
              width={100}
            />
          </sc.ProfileContainer>
        </sc.Container>
      </sc.Main>

      <footer></footer>
    </div>
  );
};

export default Home;
